name: Sieve Test

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

env:
  IMAGE_NAMESPACE: ghcr.io/sieve-project/action

jobs:
  casskop-operator:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      KUBECONFIG: /home/runner/.kube/config
    steps:
      - uses: actions/checkout@v2
      - name: Setup Git
        run: |
          git config --global user.name "sieve"
          git config --global user.email "sieve@sieve.com"
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
      - name: Setup GitHub Package Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Install Python Packages
        run: |
          pip install -r requirements.txt
      - name: Install Kind
        run: |
          go get sigs.k8s.io/kind
          kind
      - name: Install Helm
        run: |
          wget https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.6.0-linux-amd64.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm
      - name: Build Image
        run: |
          python3 build.py -p casskop-operator -m learn -d $IMAGE_NAMESPACE
          python3 build.py -p casskop-operator -m time-travel  -d $IMAGE_NAMESPACE
          python3 build.py -p casskop-operator -m obs-gap  -d $IMAGE_NAMESPACE
      - name: Sieve Learn
        run: |
          python3 sieve.py -p casskop-operator -t recreate -s learn -d $IMAGE_NAMESPACE
          python3 sieve.py -p casskop-operator -t reducepdb -s learn -d $IMAGE_NAMESPACE
          python3 sieve.py -p casskop-operator -t scaledown-to-zero -s learn -d $IMAGE_NAMESPACE
      - uses: actions/upload-artifact@v2
        with:
          name: sieve-casskop-data
          path: data/casskop-operator
      - name: Sieve Test
        run: |
          python3 sieve.py -p casskop-operator -t recreate -d $IMAGE_NAMESPACE
          python3 sieve.py -p casskop-operator -t reducepdb -d $IMAGE_NAMESPACE
          python3 sieve.py -p casskop-operator -t scaledown-to-zero -d $IMAGE_NAMESPACE
      - uses: actions/upload-artifact@v2
        with:
          name: sieve-casskop-artifact
          path: log