apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: multimesh-v19x
spec:
  version: "1.9.2"
  global: false
  meshPolicy:
    mtlsMode: STRICT
  multiMesh: true
  istioCoreDNS:
    enabled: true
  citadel:
    caSecretName: "cacerts"
  proxy:
    image: "docker.io/istio/proxyv2:1.9.2"
  jwtPolicy: "first-party-jwt"
