---
- name: Install Docker
  hosts: ec2
  become: true
  vars_files:
    - vars/default.yaml

  tasks:
    - name: Install pip3
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install python packages using pip
      pip:
        name: "{{ PYTHON_PACKAGES }}"
        state: present
