name: Sieve Test
'on':
  pull_request: null
  workflow_dispatch: null
  schedule:
  - cron: 0 4 * * *
env:
  IMAGE_NAMESPACE: ghcr.io/sieve-project/action
jobs:
  cassandra-operator:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      KUBECONFIG: /home/runner/.kube/config
    steps:
    - uses: actions/checkout@v2
    - name: Setup Git
      run: 'git config --global user.name "sieve"

        git config --global user.email "sieve@sieve.com"'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7
    - name: Setup GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor
        }}" --password-stdin
    - name: Install Python Packages
      run: pip install -r requirements.txt
    - name: Install Kind
      run: 'go get sigs.k8s.io/kind

        kind'
    - name: Install Helm
      run: 'wget https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz

        tar -zxvf helm-v3.6.0-linux-amd64.tar.gz

        sudo mv linux-amd64/helm /usr/local/bin/helm

        helm'
    - name: Build Image
      run: 'python3 build.py -p cassandra-operator -m learn -d $IMAGE_NAMESPACE

        python3 build.py -p cassandra-operator -m time-travel -d $IMAGE_NAMESPACE

        python3 build.py -p cassandra-operator -m observability-gap -d $IMAGE_NAMESPACE'
    - name: Sieve Learn
      run: 'python3 sieve.py -p cassandra-operator -t recreate -s learn-twice -d $IMAGE_NAMESPACE

        python3 sieve.py -p cassandra-operator -t scaledown -s learn-twice -d $IMAGE_NAMESPACE

        python3 sieve.py -p cassandra-operator -t scaledown-scaleup -s learn-twice
        -d $IMAGE_NAMESPACE'
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-cassandra-operator-data
        path: data/cassandra-operator
    - name: Sieve Test
      run: 'python3 reprod.py -p cassandra-operator -b obs-gap-1 -d $IMAGE_NAMESPACE

        python3 reprod.py -p cassandra-operator -b time-travel-1 -d $IMAGE_NAMESPACE

        python3 reprod.py -p cassandra-operator -b time-travel-2 -d $IMAGE_NAMESPACE'
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-cassandra-operator-log
        path: log
  cass-operator:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      KUBECONFIG: /home/runner/.kube/config
    steps:
    - uses: actions/checkout@v2
    - name: Setup Git
      run: 'git config --global user.name "sieve"

        git config --global user.email "sieve@sieve.com"'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7
    - name: Setup GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor
        }}" --password-stdin
    - name: Install Python Packages
      run: pip install -r requirements.txt
    - name: Install Kind
      run: 'go get sigs.k8s.io/kind

        kind'
    - name: Install Helm
      run: 'wget https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz

        tar -zxvf helm-v3.6.0-linux-amd64.tar.gz

        sudo mv linux-amd64/helm /usr/local/bin/helm

        helm'
    - name: Build Image
      run: 'python3 build.py -p cass-operator -m learn -d $IMAGE_NAMESPACE

        python3 build.py -p cass-operator -m time-travel -d $IMAGE_NAMESPACE'
    - name: Sieve Learn
      run: python3 sieve.py -p cass-operator -t recreate -s learn-twice -d $IMAGE_NAMESPACE
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-cass-operator-data
        path: data/cass-operator
    - name: Sieve Test
      run: python3 reprod.py -p cass-operator -b time-travel-1 -d $IMAGE_NAMESPACE
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-cass-operator-log
        path: log
  casskop-operator:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      KUBECONFIG: /home/runner/.kube/config
    steps:
    - uses: actions/checkout@v2
    - name: Setup Git
      run: 'git config --global user.name "sieve"

        git config --global user.email "sieve@sieve.com"'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7
    - name: Setup GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor
        }}" --password-stdin
    - name: Install Python Packages
      run: pip install -r requirements.txt
    - name: Install Kind
      run: 'go get sigs.k8s.io/kind

        kind'
    - name: Install Helm
      run: 'wget https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz

        tar -zxvf helm-v3.6.0-linux-amd64.tar.gz

        sudo mv linux-amd64/helm /usr/local/bin/helm

        helm'
    - name: Build Image
      run: 'python3 build.py -p casskop-operator -m learn -d $IMAGE_NAMESPACE

        python3 build.py -p casskop-operator -m time-travel -d $IMAGE_NAMESPACE

        python3 build.py -p casskop-operator -m observability-gap -d $IMAGE_NAMESPACE'
    - name: Sieve Learn
      run: 'python3 sieve.py -p casskop-operator -t scaledown -s learn-twice -d $IMAGE_NAMESPACE

        python3 sieve.py -p casskop-operator -t recreate -s learn-twice -d $IMAGE_NAMESPACE

        python3 sieve.py -p casskop-operator -t scaledown-to-zero -s learn-twice -d
        $IMAGE_NAMESPACE

        python3 sieve.py -p casskop-operator -t reducepdb -s learn-twice -d $IMAGE_NAMESPACE'
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-casskop-operator-data
        path: data/casskop-operator
    - name: Sieve Test
      run: 'python3 reprod.py -p casskop-operator -b obs-gap-1 -d $IMAGE_NAMESPACE

        python3 reprod.py -p casskop-operator -b obs-gap-2 -d $IMAGE_NAMESPACE

        python3 reprod.py -p casskop-operator -b time-travel-1 -d $IMAGE_NAMESPACE

        python3 reprod.py -p casskop-operator -b time-travel-2 -d $IMAGE_NAMESPACE'
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-casskop-operator-log
        path: log
  nifikop-operator:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      KUBECONFIG: /home/runner/.kube/config
    steps:
    - uses: actions/checkout@v2
    - name: Setup Git
      run: 'git config --global user.name "sieve"

        git config --global user.email "sieve@sieve.com"'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7
    - name: Setup GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor
        }}" --password-stdin
    - name: Install Python Packages
      run: pip install -r requirements.txt
    - name: Install Kind
      run: 'go get sigs.k8s.io/kind

        kind'
    - name: Install Helm
      run: 'wget https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz

        tar -zxvf helm-v3.6.0-linux-amd64.tar.gz

        sudo mv linux-amd64/helm /usr/local/bin/helm

        helm'
    - name: Build Image
      run: 'python3 build.py -p nifikop-operator -m learn -d $IMAGE_NAMESPACE

        python3 build.py -p nifikop-operator -m atomicity-violation -d $IMAGE_NAMESPACE'
    - name: Sieve Learn
      run: python3 sieve.py -p nifikop-operator -t change-config -s learn-twice -d
        $IMAGE_NAMESPACE
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-nifikop-operator-data
        path: data/nifikop-operator
    - name: Sieve Test
      run: python3 reprod.py -p nifikop-operator -b atom-vio-1 -d $IMAGE_NAMESPACE
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-nifikop-operator-log
        path: log
  rabbitmq-operator:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      KUBECONFIG: /home/runner/.kube/config
    steps:
    - uses: actions/checkout@v2
    - name: Setup Git
      run: 'git config --global user.name "sieve"

        git config --global user.email "sieve@sieve.com"'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7
    - name: Setup GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor
        }}" --password-stdin
    - name: Install Python Packages
      run: pip install -r requirements.txt
    - name: Install Kind
      run: 'go get sigs.k8s.io/kind

        kind'
    - name: Install Helm
      run: 'wget https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz

        tar -zxvf helm-v3.6.0-linux-amd64.tar.gz

        sudo mv linux-amd64/helm /usr/local/bin/helm

        helm'
    - name: Build Image
      run: 'python3 build.py -p rabbitmq-operator -m learn -d $IMAGE_NAMESPACE

        python3 build.py -p rabbitmq-operator -m time-travel -d $IMAGE_NAMESPACE

        python3 build.py -p rabbitmq-operator -m observability-gap -d $IMAGE_NAMESPACE

        python3 build.py -p rabbitmq-operator -m atomicity-violation -d $IMAGE_NAMESPACE'
    - name: Sieve Learn
      run: 'python3 sieve.py -p rabbitmq-operator -t recreate -s learn-twice -d $IMAGE_NAMESPACE

        python3 sieve.py -p rabbitmq-operator -t resize-pvc-atomic -s learn-twice
        -d $IMAGE_NAMESPACE

        python3 sieve.py -p rabbitmq-operator -t resize-pvc -s learn-twice -d $IMAGE_NAMESPACE

        python3 sieve.py -p rabbitmq-operator -t scaleup-scaledown -s learn-twice
        -d $IMAGE_NAMESPACE'
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-rabbitmq-operator-data
        path: data/rabbitmq-operator
    - name: Sieve Test
      run: 'python3 reprod.py -p rabbitmq-operator -b atom-vio-1 -d $IMAGE_NAMESPACE

        python3 reprod.py -p rabbitmq-operator -b obs-gap-1 -d $IMAGE_NAMESPACE

        python3 reprod.py -p rabbitmq-operator -b time-travel-1 -d $IMAGE_NAMESPACE

        python3 reprod.py -p rabbitmq-operator -b time-travel-2 -d $IMAGE_NAMESPACE'
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-rabbitmq-operator-log
        path: log
  mongodb-operator:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      KUBECONFIG: /home/runner/.kube/config
    steps:
    - uses: actions/checkout@v2
    - name: Setup Git
      run: 'git config --global user.name "sieve"

        git config --global user.email "sieve@sieve.com"'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7
    - name: Setup GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor
        }}" --password-stdin
    - name: Install Python Packages
      run: pip install -r requirements.txt
    - name: Install Kind
      run: 'go get sigs.k8s.io/kind

        kind'
    - name: Install Helm
      run: 'wget https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz

        tar -zxvf helm-v3.6.0-linux-amd64.tar.gz

        sudo mv linux-amd64/helm /usr/local/bin/helm

        helm'
    - name: Build Image
      run: 'python3 build.py -p mongodb-operator -m learn -d $IMAGE_NAMESPACE

        python3 build.py -p mongodb-operator -m time-travel -d $IMAGE_NAMESPACE'
    - name: Sieve Learn
      run: 'python3 sieve.py -p mongodb-operator -t recreate -s learn-twice -d $IMAGE_NAMESPACE

        python3 sieve.py -p mongodb-operator -t disable-enable-shard -s learn-twice
        -d $IMAGE_NAMESPACE

        python3 sieve.py -p mongodb-operator -t disable-enable-arbiter -s learn-twice
        -d $IMAGE_NAMESPACE'
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-mongodb-operator-data
        path: data/mongodb-operator
    - name: Sieve Test
      run: 'python3 reprod.py -p mongodb-operator -b time-travel-1 -d $IMAGE_NAMESPACE

        python3 reprod.py -p mongodb-operator -b time-travel-2 -d $IMAGE_NAMESPACE

        python3 reprod.py -p mongodb-operator -b time-travel-3 -d $IMAGE_NAMESPACE'
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-mongodb-operator-log
        path: log
  xtradb-operator:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      KUBECONFIG: /home/runner/.kube/config
    steps:
    - uses: actions/checkout@v2
    - name: Setup Git
      run: 'git config --global user.name "sieve"

        git config --global user.email "sieve@sieve.com"'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7
    - name: Setup GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor
        }}" --password-stdin
    - name: Install Python Packages
      run: pip install -r requirements.txt
    - name: Install Kind
      run: 'go get sigs.k8s.io/kind

        kind'
    - name: Install Helm
      run: 'wget https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz

        tar -zxvf helm-v3.6.0-linux-amd64.tar.gz

        sudo mv linux-amd64/helm /usr/local/bin/helm

        helm'
    - name: Build Image
      run: 'python3 build.py -p xtradb-operator -m learn -d $IMAGE_NAMESPACE

        python3 build.py -p xtradb-operator -m time-travel -d $IMAGE_NAMESPACE'
    - name: Sieve Learn
      run: 'python3 sieve.py -p xtradb-operator -t recreate -s learn-twice -d $IMAGE_NAMESPACE

        python3 sieve.py -p xtradb-operator -t disable-enable-proxysql -s learn-twice
        -d $IMAGE_NAMESPACE

        python3 sieve.py -p xtradb-operator -t disable-enable-haproxy -s learn-twice
        -d $IMAGE_NAMESPACE'
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-xtradb-operator-data
        path: data/xtradb-operator
    - name: Sieve Test
      run: 'python3 reprod.py -p xtradb-operator -b time-travel-1 -d $IMAGE_NAMESPACE

        python3 reprod.py -p xtradb-operator -b time-travel-2 -d $IMAGE_NAMESPACE

        python3 reprod.py -p xtradb-operator -b time-travel-3 -d $IMAGE_NAMESPACE'
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-xtradb-operator-log
        path: log
  yugabyte-operator:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      KUBECONFIG: /home/runner/.kube/config
    steps:
    - uses: actions/checkout@v2
    - name: Setup Git
      run: 'git config --global user.name "sieve"

        git config --global user.email "sieve@sieve.com"'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7
    - name: Setup GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor
        }}" --password-stdin
    - name: Install Python Packages
      run: pip install -r requirements.txt
    - name: Install Kind
      run: 'go get sigs.k8s.io/kind

        kind'
    - name: Install Helm
      run: 'wget https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz

        tar -zxvf helm-v3.6.0-linux-amd64.tar.gz

        sudo mv linux-amd64/helm /usr/local/bin/helm

        helm'
    - name: Build Image
      run: 'python3 build.py -p yugabyte-operator -m learn -d $IMAGE_NAMESPACE

        python3 build.py -p yugabyte-operator -m time-travel -d $IMAGE_NAMESPACE

        python3 build.py -p yugabyte-operator -m observability-gap -d $IMAGE_NAMESPACE'
    - name: Sieve Learn
      run: 'python3 sieve.py -p yugabyte-operator -t disable-enable-tuiport -s learn-twice
        -d $IMAGE_NAMESPACE

        python3 sieve.py -p yugabyte-operator -t disable-enable-tls -s learn-twice
        -d $IMAGE_NAMESPACE

        python3 sieve.py -p yugabyte-operator -t scaleup-scaledown-tserver -s learn-twice
        -d $IMAGE_NAMESPACE'
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-yugabyte-operator-data
        path: data/yugabyte-operator
    - name: Sieve Test
      run: 'python3 reprod.py -p yugabyte-operator -b obs-gap-1 -d $IMAGE_NAMESPACE

        python3 reprod.py -p yugabyte-operator -b time-travel-1 -d $IMAGE_NAMESPACE

        python3 reprod.py -p yugabyte-operator -b time-travel-2 -d $IMAGE_NAMESPACE'
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-yugabyte-operator-log
        path: log
  zookeeper-operator:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      KUBECONFIG: /home/runner/.kube/config
    steps:
    - uses: actions/checkout@v2
    - name: Setup Git
      run: 'git config --global user.name "sieve"

        git config --global user.email "sieve@sieve.com"'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7
    - name: Setup GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor
        }}" --password-stdin
    - name: Install Python Packages
      run: pip install -r requirements.txt
    - name: Install Kind
      run: 'go get sigs.k8s.io/kind

        kind'
    - name: Install Helm
      run: 'wget https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz

        tar -zxvf helm-v3.6.0-linux-amd64.tar.gz

        sudo mv linux-amd64/helm /usr/local/bin/helm

        helm'
    - name: Build Image
      run: 'python3 build.py -p zookeeper-operator -m learn -d $IMAGE_NAMESPACE

        python3 build.py -p zookeeper-operator -m time-travel -d $IMAGE_NAMESPACE'
    - name: Sieve Learn
      run: 'python3 sieve.py -p zookeeper-operator -t recreate -s learn-twice -d $IMAGE_NAMESPACE

        python3 sieve.py -p zookeeper-operator -t scaledown-scaleup -s learn-twice
        -d $IMAGE_NAMESPACE'
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-zookeeper-operator-data
        path: data/zookeeper-operator
    - name: Sieve Test
      run: 'python3 reprod.py -p zookeeper-operator -b time-travel-1 -d $IMAGE_NAMESPACE

        python3 reprod.py -p zookeeper-operator -b time-travel-2 -d $IMAGE_NAMESPACE'
    - uses: actions/upload-artifact@v2
      with:
        name: sieve-zookeeper-operator-log
        path: log
